# Generated by Django 3.1.5 on 2021-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Course Name', max_length=100)),
                ('description', models.TextField(help_text='Course Description', max_length=400)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('current_occupancy', models.IntegerField(default=0)),
                ('maximum_occupancy', models.IntegerField(default=10)),
                ('location', models.TextField(default='Main Building', max_length=100)),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Rental Name', max_length=100)),
                ('description', models.TextField(help_text='Rental Description', max_length=400)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('current_occupancy', models.IntegerField(default=1)),
                ('maximum_occupancy', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Service Name', max_length=100)),
                ('description', models.TextField(help_text='Service Description', max_length=400)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('current_occupancy', models.IntegerField(default=1)),
                ('maximum_occupancy', models.IntegerField(default=1)),
                ('location', models.TextField(default='Main Building', max_length=100)),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
    ]
