# Generated by Django 3.1.5 on 2021-04-20 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20210420_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='type',
            new_name='offering_type',
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_four', models.IntegerField(default=1324)),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express')], default='Visa', max_length=40)),
                ('expiry_month', models.IntegerField(default=11)),
                ('expiry_year', models.IntegerField(default=21)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
